name: _Template Build

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Tag to apply to the built Docker image'
        required: true
        type: string
      working-directory:
        description: 'Directory containing the Dockerfile to build'
        required: false
        type: string
        default: '.'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build
        working-directory: ${{ inputs.working-directory }}
        run: docker build -t "${{ inputs.image-name }}" .
